export const artisticThemes = {
	ancient_woodland: {
		name: "Ancient Woodland",
		description: "Deep forest greens and mossy textures for a lush canopy feel",
		bg: "#064E3B",
		text: "#D1FAE5",
		water: "#022C22",
		parks: "#14532D",
		road_motorway: "#FDE047", 
		road_primary: "#A7F3D0",
		road_secondary: "#34D399",
		road_tertiary: "#10B981",
		road_residential: "#065F46",
		road_default: "#34D399",
		route: "#EF4444"
	},
	arctic_frost: {
		name: "Arctic Frost",
		description: "Pale blues and crisp whites for a frozen landscape look",
		bg: "#F0F9FF",
		text: "#0C4A6E",
		water: "#BAE6FD",
		parks: "#E0F2FE",
		road_motorway: "#0EA5E9",
		road_primary: "#38BDF8",
		road_secondary: "#7DD3FC",
		road_tertiary: "#BAE6FD",
		road_residential: "#E0F2FE",
		road_default: "#7DD3FC",
		route: "#F97316"
	},
	arid_canyon: {
		name: "Arid Canyon",
		description: "Dusty ochre and sun-scorched earth tones for desert landscapes",
		bg: "#FFFBEB",
		text: "#451A03",
		water: "#EAB308",
		parks: "#FEF3C7",
		road_motorway: "#9A3412",
		road_primary: "#C2410C",
		road_secondary: "#EA580C",
		road_tertiary: "#F97316",
		road_residential: "#FDE68A",
		road_default: "#EA580C",
		route: "#22D3EE"
	},
	aurora_glow: {
		name: "Aurora Glow",
		description: "Iridescent greens and pinks inspired by northern lights",
		bg: "#071428",
		text: "#E6FFF7",
		water: "#0EA5A5",
		parks: "#9EEAD6",
		road_motorway: "#7CF9D2",
		road_primary: "#5EEAD4",
		road_secondary: "#3BD6B6",
		road_tertiary: "#2FAF95",
		road_residential: "#1F7F6A",
		road_default: "#3BD6B6",
		route: "#F472B6"
	},
	autumn_whisper: {
		name: "Autumn Whisper",
		description: "Burned oranges and deep ochre tints of fallen leaves",
		bg: "#451A03",
		text: "#FEF3C7",
		water: "#78350F",
		parks: "#92400E",
		road_motorway: "#F59E0B",
		road_primary: "#FBBF24",
		road_secondary: "#FCD34D",
		road_tertiary: "#FDE68A",
		road_residential: "#FEF3C7",
		road_default: "#FBBF24",
		route: "#3B82F6"
	},
	blueprint_classic: {
		name: "Blueprint Classic",
		description: "Technical cyanotype style for an architectural, engineered feel",
		bg: "#1E3A8A",
		text: "#DBEAFE",
		water: "#172554",
		parks: "#1E40AF",
		road_motorway: "#FFFFFF",
		road_primary: "#BFDBFE",
		road_secondary: "#93C5FD",
		road_tertiary: "#60A5FA",
		road_residential: "#3B82F6",
		road_default: "#93C5FD",
		route: "#FACC15"
	},
	charcoal_sketch: {
		name: "Charcoal Sketch",
		description: "The look of graphite on textured heavy-grain paper",
		bg: "#E5E7EB",
		text: "#1F2937",
		water: "#D1D5DB",
		parks: "#9CA3AF",
		road_motorway: "#111827",
		road_primary: "#374151",
		road_secondary: "#4B5563",
		road_tertiary: "#6B7280",
		road_residential: "#F3F4F6",
		road_default: "#4B5563",
		route: "#EF4444"
	},
	copper_patina: {
		name: "Copper Patina",
		description: "Aged bronze and oxidized turquoise for a weathered metal look",
		bg: "#134E4A",
		text: "#CCFBF1",
		water: "#042F2E",
		parks: "#0F766E",
		road_motorway: "#2DD4BF",
		road_primary: "#99F6E4",
		road_secondary: "#B45309",
		road_tertiary: "#D97706",
		road_residential: "#115E59",
		road_default: "#2DD4BF",
		route: "#FACC15"
	},
	cyber_glitch: {
		name: "Cyber Glitch",
		description: "Electric purples and neon yellows for a digital future",
		bg: "#2E1065",
		text: "#F0ABFC",
		water: "#4C1D95",
		parks: "#581C87",
		road_motorway: "#FACC15",
		road_primary: "#EAB308",
		road_secondary: "#A855F7",
		road_tertiary: "#C084FC",
		road_residential: "#D8B4FE",
		road_default: "#A855F7",
		route: "#22D3EE"
	},
	cyber_noir: {
		name: "Cyber Noir",
		description: "Dark background with vibrant neon stripe palette",
		bg: "#0B0B16",
		text: "#00E5E5",
		gradient_color: "#0B0B16",
		water: "#071020",
		parks: "#111122",
		road_motorway: "#FF2AE6",
		road_primary: "#00E5FF",
		road_secondary: "#00BEBE",
		road_tertiary: "#008F95",
		road_residential: "#005E66",
		road_default: "#008F95",
		route: "#EAB308"
	},
	desert_mirage: {
		name: "Desert Mirage",
		description: "Sun-bleached sands and warm terracotta tones",
		bg: "#FEF3C7",
		text: "#92400E",
		water: "#FDE68A",
		parks: "#FCD34D",
		road_motorway: "#B45309",
		road_primary: "#D97706",
		road_secondary: "#F59E0B",
		road_tertiary: "#FB7185",
		road_residential: "#FFEDD5",
		road_default: "#F59E0B",
		route: "#3B82F6"
	},
	deep_ocean: {
		name: "Deep Ocean",
		description: "Dark navy depths and teal currents",
		bg: "#082F49",
		text: "#E0F2FE",
		water: "#0C4A6E",
		parks: "#075985",
		road_motorway: "#0EA5E9",
		road_primary: "#38BDF8",
		road_secondary: "#7DD3FC",
		road_tertiary: "#BAE6FD",
		road_residential: "#0C4A6E",
		road_default: "#38BDF8",
		route: "#FACC15"
	},
	dark_gold: {
		name: "Dark Gold",
		description: "Luxurious dark background with warm gold accents",
		bg: "#0B0A09",
		text: "#F6E7C1",
		water: "#061022",
		parks: "#26221A",
		road_motorway: "#D4AF37",
		road_primary: "#E6C07A",
		road_secondary: "#A3752B",
		road_tertiary: "#8B5E3C",
		road_residential: "#2F2B23",
		road_default: "#A3752B",
		route: "#22D3EE"
	},
	emerald_valley: {
		name: "Emerald Valley",
		description: "Lush mossy greens and deep forest tones",
		bg: "#022C22",
		text: "#D1FAE5",
		water: "#064E3B",
		parks: "#065F46",
		road_motorway: "#10B981",
		road_primary: "#34D399",
		road_secondary: "#059669",
		road_tertiary: "#047857",
		road_residential: "#064E3B",
		road_default: "#059669",
		route: "#F97316"
	},
	ethereal_ghost: {
		name: "Ethereal Ghost",
		description: "Ultra-minimalist light greys and silvery whites",
		bg: "#FAFAFA",
		text: "#404040",
		water: "#F5F5F5",
		parks: "#E5E5E5",
		road_motorway: "#262626",
		road_primary: "#525252",
		road_secondary: "#A3A3A3",
		road_tertiary: "#D4D4D4",
		road_residential: "#F5F5F5",
		road_default: "#A3A3A3",
		route: "#3B82F6"
	},
	forest_shadow: {
		name: "Forest Shadow",
		description: "Moody, deep evergreen tones with misty highlights",
		bg: "#052E16",
		text: "#ECFDF5",
		water: "#022C22",
		parks: "#064E3B",
		road_motorway: "#10B981",
		road_primary: "#34D399",
		road_secondary: "#059669",
		road_tertiary: "#047857",
		road_residential: "#064E3B",
		road_default: "#059669",
		route: "#EF4444"
	},
	golden_era: {
		name: "Golden Era",
		description: "Rich yellows and deep browns recalling classic cartography",
		bg: "#FEFCE8",
		text: "#713F12",
		water: "#FEF08A",
		parks: "#FDE047",
		road_motorway: "#854D0E",
		road_primary: "#A16207",
		road_secondary: "#CA8A04",
		road_tertiary: "#EAB308",
		road_residential: "#FACC15",
		road_default: "#CA8A04",
		route: "#3B82F6"
	},
	lavender_mist: {
		name: "Lavender Mist",
		description: "Soft purples and muted greys - dreamy cartography",
		bg: "#F5F3FF",
		text: "#4C1D95",
		water: "#EDE9FE",
		parks: "#DDD6FE",
		road_motorway: "#5B21B6",
		road_primary: "#6D28D9",
		road_secondary: "#7C3AED",
		road_tertiary: "#8B5CF6",
		road_residential: "#A78BFA",
		road_default: "#7C3AED",
		route: "#10B981"
	},
	mint_fizz: {
		name: "Mint Fizz",
		description: "Fresh minty pastels for a calm, modern map",
		bg: "#F4FFFB",
		text: "#09332A",
		water: "#DFFCF4",
		parks: "#CCFBF1",
		road_motorway: "#34D399",
		road_primary: "#6EE7B7",
		road_secondary: "#4ADE80",
		road_tertiary: "#86EFAC",
		road_residential: "#D1FAE5",
		road_default: "#4ADE80",
		route: "#EF4444"
	},
	midnight_neon: {
		name: "Midnight Neon",
		description: "Black ink nights with neon accents for dramatic contrast",
		bg: "#030014",
		text: "#EAF7FF",
		water: "#062A66",
		parks: "#1B2B3B",
		road_motorway: "#00F5A0",
		road_primary: "#00E5FF",
		road_secondary: "#FF00C8",
		road_tertiary: "#9B7CFF",
		road_residential: "#6EE7B7",
		road_default: "#00E5FF",
		route: "#FFFF00"
	},
	monochrome_pro: {
		name: "Monochrome Pro",
		description: "Balanced greyscale for professional architectural maps",
		bg: "#FFFFFF",
		text: "#18181B",
		water: "#F4F4F5",
		parks: "#E4E4E7",
		road_motorway: "#18181B",
		road_primary: "#3F3F46",
		road_secondary: "#52525B",
		road_tertiary: "#71717A",
		road_residential: "#A1A1AA",
		road_default: "#52525B",
		route: "#EF4444"
	},
	mangrove_maze: {
		name: "Mangrove Maze",
		description: "Murky swamp tones and brackish water for coastal wetlands",
		bg: "#111827",
		text: "#A7F3D0",
		water: "#0F172A",
		parks: "#065F46",
		road_motorway: "#84CC16",
		road_primary: "#65A30D",
		road_secondary: "#4D7C0F",
		road_tertiary: "#3F6212",
		road_residential: "#1A2E05",
		road_default: "#4D7C0F",
		route: "#F472B6"
	},
	paper_heritage: {
		name: "Paper Heritage",
		description: "Soft sepia tones and inked roads for vintage prints",
		bg: "#FBF6EE",
		text: "#3B2F2F",
		water: "#EAE2D6",
		parks: "#F5E9D4",
		road_motorway: "#7A4B2D",
		road_primary: "#9A6B3A",
		road_secondary: "#B77A3A",
		road_tertiary: "#D29A55",
		road_residential: "#F1E2CF",
		road_default: "#B77A3A",
		route: "#3B82F6"
	},
	riverine_flow: {
		name: "Riverine Flow",
		description: "Cool aquas and deep teals emphasizing the movement of water",
		bg: "#ECFEFF",
		text: "#083344",
		water: "#06B6D4",
		parks: "#CFFAFE",
		road_motorway: "#0E7490",
		road_primary: "#22D3EE",
		road_secondary: "#67E8F9",
		road_tertiary: "#A5F3FC",
		road_residential: "#E0F2FE",
		road_default: "#22D3EE",
		route: "#F97316"
	},
	retro_synth: {
		name: "Retro Synth",
		description: "80s outrun aesthetic with neon magentas and electric blues",
		bg: "#1A0B2E",
		text: "#FF00FF",
		water: "#2D0052",
		parks: "#4C1D95",
		road_motorway: "#FF00FF",
		road_primary: "#00FFFF",
		road_secondary: "#BD00FF",
		road_tertiary: "#7000FF",
		road_residential: "#4B0082",
		road_default: "#BD00FF",
		route: "#FFFF00"
	},
	royal_velvet: {
		name: "Royal Velvet",
		description: "Deep regal purples paired with rich metallic gold",
		bg: "#2E1065",
		text: "#FEF08A",
		water: "#1E1B4B",
		parks: "#4C1D95",
		road_motorway: "#EAB308",
		road_primary: "#FACC15",
		road_secondary: "#A855F7",
		road_tertiary: "#C084FC",
		road_residential: "#581C87",
		road_default: "#A855F7",
		route: "#22D3EE"
	},
	rustic_clay: {
		name: "Rustic Clay",
		description: "Earthy reds and warm oranges - sun-baked urban style",
		bg: "#FFF7ED",
		text: "#7C2D12",
		water: "#FFEDD5",
		parks: "#FED7AA",
		road_motorway: "#9A3412",
		road_primary: "#C2410C",
		road_secondary: "#EA580C",
		road_tertiary: "#F97316",
		road_residential: "#FB923C",
		road_default: "#EA580C",
		route: "#3B82F6"
	},
	sakura_bloom: {
		name: "Sakura Bloom",
		description: "Soft cherry blossom pinks and delicate cream tones",
		bg: "#FFF1F2",
		text: "#881337",
		water: "#FFE4E6",
		parks: "#FBCFE8",
		road_motorway: "#FB7185",
		road_primary: "#FDA4AF",
		road_secondary: "#F9A8D4",
		road_tertiary: "#F472B6",
		road_residential: "#FFF5F7",
		road_default: "#F9A8D4",
		route: "#10B981"
	},
	solar_flare: {
		name: "Solar Flare",
		description: "High-energy oranges and blacks inspired by sunspots",
		bg: "#000000",
		text: "#FB923C",
		water: "#1C1917",
		parks: "#292524",
		road_motorway: "#F97316",
		road_primary: "#FB923C",
		road_secondary: "#EA580C",
		road_tertiary: "#9A3412",
		road_residential: "#44403C",
		road_default: "#EA580C",
		route: "#22D3EE"
	},
	steel_metropolis: {
		name: "Steel Metropolis",
		description: "Cold slate and concrete greys for a modern cityscape aesthetic",
		bg: "#334155",
		text: "#F1F5F9",
		water: "#1E293B",
		parks: "#475569",
		road_motorway: "#FFFFFF",
		road_primary: "#E2E8F0",
		road_secondary: "#CBD5E1",
		road_tertiary: "#94A3B8",
		road_residential: "#64748B",
		road_default: "#CBD5E1",
		route: "#F97316"
	},
	sunset_blush: {
		name: "Sunset Blush",
		description: "Warm pinks and corals mimicking a coastal sunset",
		bg: "#FFF5F7",
		text: "#6B1226",
		water: "#FFE4E6",
		parks: "#FFD6E0",
		road_motorway: "#FF7A59",
		road_primary: "#FF6B6B",
		road_secondary: "#FF8FA3",
		road_tertiary: "#FFB4C6",
		road_residential: "#FFECEC",
		road_default: "#FF6B6B",
		route: "#10B981"
	},
	volcanic_ash: {
		name: "Volcanic Ash",
		description: "Deep charcoal and glowing embers - high drama style",
		bg: "#1C1917",
		text: "#FAFAF9",
		water: "#0C0A09",
		parks: "#292524",
		road_motorway: "#EF4444",
		road_primary: "#F87171",
		road_secondary: "#B91C1C",
		road_tertiary: "#7F1D1D",
		road_residential: "#450A0A",
		road_default: "#B91C1C",
		route: "#FACC15"
	}
	autumn: {
		name: "Autumn",
		description: "Burnt oranges, deep reds, golden yellows - seasonal warmth",
		bg: "#FBF7F0",
		text: "#8B4513",
		water: "#D8CFC0",
		parks: "#E8E0D0",
		road_motorway: "#8B2500",
		road_primary: "#B8450A",
		road_secondary: "#CC7A30",
		road_default: "#CC7A30",
		route: "#EF4444"
	},
	blueprint: {
		name: "Blueprint",
		description: "Classic architectural blueprint - technical drawing aesthetic",
		bg: "#1A3A5C",
		text: "#E8F4FF",
		water: "#0F2840",
		parks: "#1E4570",
		road_motorway: "#E8F4FF",
		road_primary: "#C5DCF0",
		road_secondary: "#9FC5E8",
		road_default: "#7BAED4",
		route: "#EF4444"
	},
	contrast_zones: {
		name: "Contrast Zones",
		description: "Strong contrast showing urban density - darker in center, lighter at edges",
		bg: "#FFFFFF",
		text: "#000000",
		water: "#B0B0B0",
		parks: "#ECECEC",
		road_motorway: "#000000",
		road_primary: "#0F0F0F",
		road_secondary: "#252525",
		road_default: "#404040",
		route: "#EF4444"
	},
	emerald: {
		name: "Emerald City",
		description: "Lush dark green aesthetic with mint accents",
		bg: "#062C22",
		text: "#E3F9F1",
		water: "#0D4536",
		parks: "#0F523E",
		road_motorway: "#4ADEB0",
		road_primary: "#2DB88F",
		road_secondary: "#249673",
		road_default: "#155C46",
		route: "#EF4444"
	},
	forest: {
		name: "Forest",
		description: "Deep greens and sage tones - organic botanical aesthetic",
		bg: "#F0F4F0",
		text: "#2D4A3E",
		water: "#B8D4D4",
		parks: "#D4E8D4",
		road_motorway: "#2D4A3E",
		road_primary: "#3D6B55",
		road_secondary: "#5A8A70",
		road_default: "#7AAA90",
		route: "#EF4444"
	},
	gradient_roads: {
		name: "Gradient Roads",
		description: "Smooth gradient from dark center to light edges with subtle features",
		bg: "#FFFFFF",
		text: "#000000",
		water: "#D5D5D5",
		parks: "#EFEFEF",
		road_motorway: "#050505",
		road_primary: "#151515",
		road_secondary: "#2A2A2A",
		road_default: "#404040",
		route: "#EF4444"
	},
	japanese_ink: {
		name: "Japanese Ink",
		description: "Traditional ink wash inspired - minimalist with subtle red accent",
		bg: "#FAF8F5",
		text: "#2C2C2C",
		water: "#E8E4E0",
		parks: "#F0EDE8",
		road_motorway: "#8B2500",
		road_primary: "#4A4A4A",
		road_secondary: "#6A6A6A",
		road_default: "#909090",
		route: "#EF4444"
	},
	midnight_blue: {
		name: "Midnight Blue",
		description: "Deep navy background with gold/copper roads - luxury atlas aesthetic",
		bg: "#0A1628",
		text: "#D4AF37",
		water: "#061020",
		parks: "#0F2235",
		road_motorway: "#D4AF37",
		road_primary: "#C9A227",
		road_secondary: "#A8893A",
		road_default: "#8B7355",
		route: "#EF4444"
	},
	monochrome_blue: {
		name: "Monochrome Blue",
		description: "Single blue color family with varying saturation - clean and cohesive",
		bg: "#F5F8FA",
		text: "#1A3A5C",
		water: "#D0E0F0",
		parks: "#E0EAF2",
		road_motorway: "#1A3A5C",
		road_primary: "#2A5580",
		road_secondary: "#4A7AA8",
		road_default: "#4A7AA8",
		route: "#EF4444"
	},
	neon_cyberpunk: {
		name: "Neon Cyberpunk",
		description: "Dark background with electric pink/cyan - bold night city vibes",
		bg: "#0D0D1A",
		text: "#00FFFF",
		water: "#0A0A15",
		parks: "#151525",
		road_motorway: "#FF00FF",
		road_primary: "#00FFFF",
		road_secondary: "#00C8C8",
		road_default: "#0098A0",
		route: "#EF4444"
	},
	noir: {
		name: "Noir",
		description: "Pure black background with white/gray roads - modern gallery aesthetic",
		bg: "#000000",
		text: "#FFFFFF",
		water: "#0A0A0A",
		parks: "#111111",
		road_motorway: "#FFFFFF",
		road_primary: "#E0E0E0",
		road_secondary: "#B0B0B0",
		road_default: "#808080",
		route: "#EF4444"
	},
	ocean: {
		name: "Ocean",
		description: "Various blues and teals - perfect for coastal cities",
		bg: "#F0F8FA",
		text: "#1A5F7A",
		water: "#B8D8E8",
		parks: "#D8EAE8",
		road_motorway: "#1A5F7A",
		road_primary: "#2A7A9A",
		road_secondary: "#4A9AB8",
		road_default: "#4A9AB8",
		route: "#EF4444"
	},
	pastel_dream: {
		name: "Pastel Dream",
		description: "Soft muted pastels with dusty blues and mauves - dreamy artistic aesthetic",
		bg: "#FAF7F2",
		text: "#5D5A6D",
		water: "#D4E4ED",
		parks: "#E8EDE4",
		road_motorway: "#7B8794",
		road_primary: "#9BA4B0",
		road_secondary: "#B5AEBB",
		road_default: "#C9C0C9",
		route: "#EF4444"
	},
	sunset: {
		name: "Sunset",
		description: "Warm oranges and pinks on soft peach - dreamy golden hour aesthetic",
		bg: "#FDF5F0",
		text: "#C45C3E",
		water: "#F0D8D0",
		parks: "#F8E8E0",
		road_motorway: "#C45C3E",
		road_primary: "#D87A5A",
		road_secondary: "#E8A088",
		road_default: "#E8A088",
		route: "#EF4444"
	},
	terracotta: {
		name: "Terracotta",
		description: "Mediterranean warmth - burnt orange and clay tones on cream",
		bg: "#F5EDE4",
		text: "#8B4513",
		water: "#A8C4C4",
		parks: "#E8E0D0",
		road_motorway: "#A0522D",
		road_primary: "#B8653A",
		road_secondary: "#C9846A",
		road_default: "#D9A08A",
		route: "#EF4444"
	},
	warm_beige: {
		name: "Warm Beige",
		description: "Earthy warm neutrals with sepia tones - vintage map aesthetic",
		bg: "#F5F0E8",
		text: "#6B5B4F",
		water: "#DDD5C8",
		parks: "#E8E4D8",
		road_motorway: "#8B7355",
		road_primary: "#A08B70",
		road_secondary: "#B5A48E",
		road_default: "#C9BBAA",
		route: "#EF4444"
	},
};
